name: vpn_check
description: Plugin used for get vpn active status for Android, iOS and MacOS
version: 0.2.2

homepage: https://github.com/cr0manty/vpn_check

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.cr0manty.vpn_check
        pluginClass: VpnCheckPlugin
      ios:
        pluginClass: VpnCheckPlugin
      macos:
        pluginClass: VpnCheckPlugin

